# Generated by gallery/generate.py; do not edit.
scoreboard objectives add sc_gallery dummy
scoreboard players add #builds sc_gallery 1
function securitycraft_gallery:clear
forceload add 160 160 191 175
fill 160 99 160 191 99 175 minecraft:stone
# A1 stock keypad
setblock 164 100 164 securitycraft:keypad
# A2 disguised keypad
setblock 170 100 164 securitycraft:keypad
data merge block 170 100 164 {disguiseEnabled:1b,Modules:[{ModuleSlot:0b,id:"securitycraft:disguise_module",count:1,components:{"securitycraft:saved_block_state":{state:{Name:"minecraft:bricks"},standing_or_wall_type:"none"}}}]}
# A2 bricks reference
setblock 170 100 168 minecraft:bricks
# A3 disguised keypad
setblock 176 100 164 securitycraft:keypad
data merge block 176 100 164 {disguiseEnabled:1b,Modules:[{ModuleSlot:0b,id:"securitycraft:disguise_module",count:1,components:{"securitycraft:saved_block_state":{state:{Name:"minecraft:oak_log",Properties:{axis:"x"}},standing_or_wall_type:"none"}}}]}
# A3 oak-log reference
setblock 176 100 168 minecraft:oak_log[axis=x]
# A4 camera support
setblock 182 100 165 minecraft:smooth_stone
# A4 reference support
setblock 182 100 169 minecraft:smooth_stone
# A4 disguised camera
setblock 182 100 164 securitycraft:security_camera[facing=north,being_viewed=false,powered=false,waterlogged=false]
data merge block 182 100 164 {disguiseEnabled:1b,Modules:[{ModuleSlot:0b,id:"securitycraft:disguise_module",count:1,components:{"securitycraft:saved_block_state":{state:{Name:"minecraft:oak_stairs",Properties:{facing:"east",half:"bottom",shape:"straight",waterlogged:"false"}},standing_or_wall_type:"none"}}}]}
# A4 oak-stairs reference
setblock 182 100 168 minecraft:oak_stairs[facing=east,half=bottom,shape=straight,waterlogged=false]
# A5 disguised redstone interface
setblock 188 100 164 securitycraft:secure_redstone_interface[facing=up,sender=true,waterlogged=false]
data merge block 188 100 164 {disguiseEnabled:1b,Modules:[{ModuleSlot:0b,id:"securitycraft:disguise_module",count:1,components:{"securitycraft:saved_block_state":{state:{Name:"minecraft:glass"},standing_or_wall_type:"none"}}}]}
# A5 glass reference
setblock 188 100 168 minecraft:glass
function securitycraft_gallery:verify_immediate
schedule function securitycraft_gallery:verify_20t 20t replace
schedule function securitycraft_gallery:verify_100t 100t replace
