# Generated by gallery/generate.py; do not edit.
scoreboard players set #failures sc_gallery 0
scoreboard players set #checked sc_gallery 0
# A1 stock keypad
execute unless block 164 100 164 securitycraft:keypad run scoreboard players add #failures sc_gallery 1
scoreboard players add #checked sc_gallery 1
# A2 disguised keypad
execute unless block 170 100 164 securitycraft:keypad run scoreboard players add #failures sc_gallery 1
scoreboard players add #checked sc_gallery 1
execute unless data block 170 100 164 {disguiseEnabled:1b,Modules:[{ModuleSlot:0b,id:"securitycraft:disguise_module",count:1,components:{"securitycraft:saved_block_state":{state:{Name:"minecraft:bricks"},standing_or_wall_type:"none"}}}]} run scoreboard players add #failures sc_gallery 1
scoreboard players add #checked sc_gallery 1
# A2 bricks reference
execute unless block 170 100 168 minecraft:bricks run scoreboard players add #failures sc_gallery 1
scoreboard players add #checked sc_gallery 1
# A3 disguised keypad
execute unless block 176 100 164 securitycraft:keypad run scoreboard players add #failures sc_gallery 1
scoreboard players add #checked sc_gallery 1
execute unless data block 176 100 164 {disguiseEnabled:1b,Modules:[{ModuleSlot:0b,id:"securitycraft:disguise_module",count:1,components:{"securitycraft:saved_block_state":{state:{Name:"minecraft:oak_log",Properties:{axis:"x"}},standing_or_wall_type:"none"}}}]} run scoreboard players add #failures sc_gallery 1
scoreboard players add #checked sc_gallery 1
# A3 oak-log reference
execute unless block 176 100 168 minecraft:oak_log[axis=x] run scoreboard players add #failures sc_gallery 1
scoreboard players add #checked sc_gallery 1
# A4 camera support
execute unless block 182 100 165 minecraft:smooth_stone run scoreboard players add #failures sc_gallery 1
scoreboard players add #checked sc_gallery 1
# A4 reference support
execute unless block 182 100 169 minecraft:smooth_stone run scoreboard players add #failures sc_gallery 1
scoreboard players add #checked sc_gallery 1
# A4 disguised camera
execute unless block 182 100 164 securitycraft:security_camera[facing=north,being_viewed=false,powered=false,waterlogged=false] run scoreboard players add #failures sc_gallery 1
scoreboard players add #checked sc_gallery 1
execute unless data block 182 100 164 {disguiseEnabled:1b,Modules:[{ModuleSlot:0b,id:"securitycraft:disguise_module",count:1,components:{"securitycraft:saved_block_state":{state:{Name:"minecraft:oak_stairs",Properties:{facing:"east",half:"bottom",shape:"straight",waterlogged:"false"}},standing_or_wall_type:"none"}}}]} run scoreboard players add #failures sc_gallery 1
scoreboard players add #checked sc_gallery 1
# A4 oak-stairs reference
execute unless block 182 100 168 minecraft:oak_stairs[facing=east,half=bottom,shape=straight,waterlogged=false] run scoreboard players add #failures sc_gallery 1
scoreboard players add #checked sc_gallery 1
# A5 disguised redstone interface
execute unless block 188 100 164 securitycraft:secure_redstone_interface[facing=up,sender=true,waterlogged=false] run scoreboard players add #failures sc_gallery 1
scoreboard players add #checked sc_gallery 1
execute unless data block 188 100 164 {disguiseEnabled:1b,Modules:[{ModuleSlot:0b,id:"securitycraft:disguise_module",count:1,components:{"securitycraft:saved_block_state":{state:{Name:"minecraft:glass"},standing_or_wall_type:"none"}}}]} run scoreboard players add #failures sc_gallery 1
scoreboard players add #checked sc_gallery 1
# A5 glass reference
execute unless block 188 100 168 minecraft:glass run scoreboard players add #failures sc_gallery 1
scoreboard players add #checked sc_gallery 1
execute unless score #builds sc_gallery matches 1 run scoreboard players add #failures sc_gallery 1
scoreboard players add #checked sc_gallery 1
