# Generated by gallery/generate.py; do not edit.
function securitycraft_gallery:verify
scoreboard players operation #20t_failures sc_gallery = #failures sc_gallery
scoreboard players operation #20t_checked sc_gallery = #checked sc_gallery
