# Generated by gallery/generate.py; do not edit.
function securitycraft_gallery:verify
scoreboard players operation #100t_failures sc_gallery = #failures sc_gallery
scoreboard players operation #100t_checked sc_gallery = #checked sc_gallery
tellraw @a [{"text":"SecurityCraft gallery 100t: "},{"score":{"name":"#100t_checked","objective":"sc_gallery"}},{"text":" checks, "},{"score":{"name":"#100t_failures","objective":"sc_gallery"}},{"text":" failures"}]
