# Generated by gallery/generate.py; do not edit.
function securitycraft_gallery:verify
scoreboard players operation #immediate_failures sc_gallery = #failures sc_gallery
scoreboard players operation #immediate_checked sc_gallery = #checked sc_gallery
tellraw @a [{"text":"SecurityCraft gallery immediate: "},{"score":{"name":"#immediate_checked","objective":"sc_gallery"}},{"text":" checks, "},{"score":{"name":"#immediate_failures","objective":"sc_gallery"}},{"text":" failures"}]
