org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=false

addon_id=bluemap-securitycraft
addon_name=BlueMap SecurityCraft Add-on
addon_version=0.1.0-alpha.2
addon_group=io.github.jan-guenter
artifact_id=bluemap-securitycraft-addon
bluemap_version=5.22-feature.backport-5.23-stateless-java-web-server-46
accepted_jar_size=33345
accepted_jar_sha256=4caccbbfaf9d413ae7d60e926069812e09da182adeb907ec2475083904d096e4
accepted_sources_jar_size=18804
accepted_sources_jar_sha256=71ba8c65532c6640b28f484aa1ef2d7900e563e7f37474d855ae01db21372694
accepted_pom_size=1370
accepted_pom_sha256=68bcd52d29167f03065d94a11f4aa2ee2530acfe2e7572df2ed8ca88b098223e
accepted_module_size=2859
accepted_module_sha256=2d705130f94b9d5a2ce1a63577d3907f71ec0d225745df957e4398e3e7547ab9
