org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=false

addon_id=bluemap-securitycraft
addon_name=BlueMap SecurityCraft Add-on
addon_version=0.1.0-alpha.2
addon_group=io.github.jan-guenter
artifact_id=bluemap-securitycraft-addon
bluemap_version=5.22-feature.backport-5.23-stateless-java-web-server-46
accepted_jar_size=36586
accepted_jar_sha256=02d3e95321fd9dfec5886c34bd6fed0f4df67ad01dc6cc6afa8a1cae9ea46071
accepted_sources_jar_size=22028
accepted_sources_jar_sha256=647bc18572f6382502106551186b6adb7f789fc3eb20c7276fa0b770ece50a34
accepted_pom_size=1370
accepted_pom_sha256=e8da1697f38c0d2f43739fcc590c146680a13f259583ddf610fac5e5c3ad9128
accepted_module_size=2859
accepted_module_sha256=584b59adfab61647f4bd1a5a32db11db8767cbb58f745c43a473aada5905e420
