#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Generate the bounded SecurityCraft disguise staging gallery."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parent
NAMESPACE = "securitycraft_gallery"
OBJECTIVE = "sc_gallery"
ENVELOPE = {
    "min_x": 160,
    "max_x": 191,
    "min_y": 99,
    "max_y": 108,
    "min_z": 160,
    "max_z": 175,
}

BRICKS_NBT = (
    '{disguiseEnabled:1b,Modules:[{ModuleSlot:0b,'
    'id:"securitycraft:disguise_module",count:1,'
    'components:{"securitycraft:saved_block_state":'
    '{state:{Name:"minecraft:bricks"},standing_or_wall_type:"none"}}}]}'
)
OAK_LOG_NBT = (
    '{disguiseEnabled:1b,Modules:[{ModuleSlot:0b,'
    'id:"securitycraft:disguise_module",count:1,'
    'components:{"securitycraft:saved_block_state":'
    '{state:{Name:"minecraft:oak_log",Properties:{axis:"x"}},'
    'standing_or_wall_type:"none"}}}]}'
)
OAK_STAIRS_NBT = (
    '{disguiseEnabled:1b,Modules:[{ModuleSlot:0b,'
    'id:"securitycraft:disguise_module",count:1,'
    'components:{"securitycraft:saved_block_state":'
    '{state:{Name:"minecraft:oak_stairs",Properties:{facing:"east",'
    'half:"bottom",shape:"straight",waterlogged:"false"}},'
    'standing_or_wall_type:"none"}}}]}'
)
GLASS_NBT = (
    '{disguiseEnabled:1b,Modules:[{ModuleSlot:0b,'
    'id:"securitycraft:disguise_module",count:1,'
    'components:{"securitycraft:saved_block_state":'
    '{state:{Name:"minecraft:glass"},standing_or_wall_type:"none"}}}]}'
)

PLACEMENTS = (
    ("A1 stock keypad", 164, 100, 164, "securitycraft:keypad", None),
    ("A2 disguised keypad", 170, 100, 164, "securitycraft:keypad", BRICKS_NBT),
    ("A2 bricks reference", 170, 100, 168, "minecraft:bricks", None),
    ("A3 disguised keypad", 176, 100, 164, "securitycraft:keypad", OAK_LOG_NBT),
    ("A3 oak-log reference", 176, 100, 168, "minecraft:oak_log[axis=x]", None),
    ("A4 camera support", 182, 100, 165, "minecraft:smooth_stone", None),
    ("A4 reference support", 182, 100, 169, "minecraft:smooth_stone", None),
    (
        "A4 disguised camera",
        182,
        100,
        164,
        "securitycraft:security_camera[facing=north,being_viewed=false,powered=false,waterlogged=false]",
        OAK_STAIRS_NBT,
    ),
    (
        "A4 oak-stairs reference",
        182,
        100,
        168,
        "minecraft:oak_stairs[facing=east,half=bottom,shape=straight,waterlogged=false]",
        None,
    ),
    (
        "A5 disguised redstone interface",
        188,
        100,
        164,
        "securitycraft:secure_redstone_interface[facing=up,sender=true,waterlogged=false]",
        GLASS_NBT,
    ),
    ("A5 glass reference", 188, 100, 168, "minecraft:glass", None),
)


def text_bytes(text: str) -> bytes:
    return (text.rstrip() + "\n").encode("utf-8")


def json_bytes(value: object) -> bytes:
    return (json.dumps(value, indent=2, sort_keys=True) + "\n").encode("utf-8")


def build_function() -> bytes:
    lines = [
        "# Generated by gallery/generate.py; do not edit.",
        f"scoreboard objectives add {OBJECTIVE} dummy",
        f"scoreboard players add #builds {OBJECTIVE} 1",
        f"function {NAMESPACE}:clear",
        "forceload add 160 160 191 175",
        "fill 160 99 160 191 99 175 minecraft:stone",
    ]
    for label, x, y, z, block, nbt in PLACEMENTS:
        lines.append(f"# {label}")
        lines.append(f"setblock {x} {y} {z} {block}")
        if nbt is not None:
            lines.append(f"data merge block {x} {y} {z} {nbt}")
    lines.extend(
        (
            f"function {NAMESPACE}:verify_immediate",
            f"schedule function {NAMESPACE}:verify_20t 20t replace",
            f"schedule function {NAMESPACE}:verify_100t 100t replace",
        )
    )
    return text_bytes("\n".join(lines))


def verify_function() -> bytes:
    lines = [
        "# Generated by gallery/generate.py; do not edit.",
        f"scoreboard players set #failures {OBJECTIVE} 0",
        f"scoreboard players set #checked {OBJECTIVE} 0",
    ]
    for label, x, y, z, block, nbt in PLACEMENTS:
        lines.append(f"# {label}")
        lines.append(
            f"execute unless block {x} {y} {z} {block} run "
            f"scoreboard players add #failures {OBJECTIVE} 1"
        )
        lines.append(f"scoreboard players add #checked {OBJECTIVE} 1")
        if nbt is not None:
            lines.append(
                f"execute unless data block {x} {y} {z} {nbt} run "
                f"scoreboard players add #failures {OBJECTIVE} 1"
            )
            lines.append(f"scoreboard players add #checked {OBJECTIVE} 1")
    lines.extend(
        (
            f"execute unless score #builds {OBJECTIVE} matches 1 run "
            f"scoreboard players add #failures {OBJECTIVE} 1",
            f"scoreboard players add #checked {OBJECTIVE} 1",
        )
    )
    return text_bytes("\n".join(lines))


def phase_function(phase: str, announce: bool) -> bytes:
    lines = [
        "# Generated by gallery/generate.py; do not edit.",
        f"function {NAMESPACE}:verify",
        f"scoreboard players operation #{phase}_failures {OBJECTIVE} = #failures {OBJECTIVE}",
        f"scoreboard players operation #{phase}_checked {OBJECTIVE} = #checked {OBJECTIVE}",
    ]
    if announce:
        payload = [
            {"text": f"SecurityCraft gallery {phase}: "},
            {"score": {"name": f"#{phase}_checked", "objective": OBJECTIVE}},
            {"text": " checks, "},
            {"score": {"name": f"#{phase}_failures", "objective": OBJECTIVE}},
            {"text": " failures"},
        ]
        lines.append("tellraw @a " + json.dumps(payload, separators=(",", ":")))
    return text_bytes("\n".join(lines))


def base_files() -> dict[Path, bytes]:
    function_root = Path(f"datapack/data/{NAMESPACE}/function")
    files = {
        Path("datapack/pack.mcmeta"): json_bytes(
            {
                "pack": {
                    "description": "ATM 1.2.0 SecurityCraft disguise BlueMap gallery",
                    "pack_format": 48,
                }
            }
        ),
        Path("datapack/data/minecraft/tags/function/load.json"): json_bytes(
            {"values": [f"{NAMESPACE}:load"]}
        ),
        function_root / "load.mcfunction": text_bytes(
            "# Generated by gallery/generate.py; do not edit.\n"
            f"scoreboard objectives add {OBJECTIVE} dummy\n"
            "forceload add 160 160 191 175"
        ),
        function_root / "clear.mcfunction": text_bytes(
            "# Generated by gallery/generate.py; do not edit.\n"
            f"schedule clear {NAMESPACE}:verify_20t\n"
            f"schedule clear {NAMESPACE}:verify_100t\n"
            "fill 160 99 160 191 108 175 minecraft:air"
        ),
        function_root / "build.mcfunction": build_function(),
        function_root / "verify.mcfunction": verify_function(),
        function_root / "verify_immediate.mcfunction": phase_function("immediate", True),
        function_root / "verify_20t.mcfunction": phase_function("20t", False),
        function_root / "verify_100t.mcfunction": phase_function("100t", True),
        function_root / "release.mcfunction": text_bytes(
            "# Generated by gallery/generate.py; do not edit.\n"
            f"schedule clear {NAMESPACE}:verify_20t\n"
            f"schedule clear {NAMESPACE}:verify_100t\n"
            "forceload remove 160 160 191 175"
        ),
    }
    return files


def sha256(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def generated_files() -> dict[Path, bytes]:
    files = base_files()
    checksum = "".join(
        f"{sha256(files[path])}  {path.as_posix()}\n" for path in sorted(files)
    )
    files[Path("SHA256SUMS")] = checksum.encode("ascii")
    return files


def write_or_check(check: bool) -> int:
    failures: list[str] = []
    for relative, payload in generated_files().items():
        path = ROOT / relative
        if check:
            if not path.is_file():
                failures.append(f"missing generated file: {relative}")
            elif path.read_bytes() != payload:
                failures.append(f"generated file differs: {relative}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(payload)
    if failures:
        print("\n".join(failures), file=sys.stderr)
        return 1
    action = "checked" if check else "wrote"
    print(f"{action} {len(generated_files())} deterministic gallery files")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    return write_or_check(args.check)


if __name__ == "__main__":
    raise SystemExit(main())
